service: myNewUrlService

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

package:
  patterns:
    - '!package.json'
    - '!package-lock.json'
    - '!node_modules/**'
    - '!scrap.txt'
  
functions:
  hello:
    handler: handler.hello # required, handler set in AWS Lambda
    name: shortUrl-sls
    description: Description of what the lambda function does.
    layers:
      - arn:aws:lambda:us-east-1:151022622966:layer:expresss-nanoid-validurl-module:1
    events:
      - http:
          path: api/
          method: post
      - http:
          path: api/{id}
          method: get
          request:
            parameters:
              paths:
                id: true


resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: shortUrlTable-sls
        AttributeDefinitions:
          - AttributeName: uniqueId
            AttributeType: S
        KeySchema:
          - AttributeName: uniqueId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1